"""Regenerate everything derived from the library.

The YAML front-matter of each library/**/*.md is the single source of truth. This
script rewrites the readable body of each prompt file, plus the catalogue, the
index and the per-role READMEs. CI runs it with --check and fails if anything
would change, so a contributor cannot land a prompt whose rendered body has
drifted from its fields.

    python tools/build.py            # write
    python tools/build.py --check    # fail if anything would change
"""
from __future__ import annotations

import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from formats import FORMATS, fidelity, render  # noqa: E402
from lib_ir import CRITERIA, ROOT, all_prompts, write_prompt  # noqa: E402

GENERATED = "<!-- GENERATED by tools/build.py from the front-matter above. Do not edit by hand. -->"
changes: list[str] = []


def emit(path: Path, content: str, check: bool) -> None:
    content = content.rstrip() + "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return
    changes.append(str(path.relative_to(ROOT)).replace("\\", "/"))
    if not check:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def score_table(p: dict) -> str:
    score = p.get("score") or {}
    rows = [f"| {label} | {score.get(key, '-')} |" for key, label in CRITERIA]
    return "\n".join([
        "| Criterion | Mark |", "| --- | --- |", *rows,
        f"| **Total** | **{score.get('total', '-')} / 20 - {score.get('verdict', '-')}** |",
    ])


def fidelity_table(p: dict) -> str:
    rows = []
    for key in FORMATS:
        f = fidelity(p, key)
        lost = ", ".join(f["criteria_lost"]) or "nothing"
        rows.append(f"| `{key}` | {f['label']} | {f['converted_total']} / 20 | {lost} |")
    return "\n".join([
        "| Flag | Framework | Score after conversion | Criteria lost |",
        "| --- | --- | --- | --- |", *rows,
    ])


def prompt_body(p: dict) -> str:
    contexts = "\n".join(f"- {c}" for c in p.get("delivery_contexts", [])) or "- (none mapped)"
    deliverables = ", ".join(p.get("deliverables", [])) or "-"
    inputs = "\n".join(f"- `[{i}]`" for i in p.get("inputs", [])) or "- (none)"
    return "\n\n".join([
        GENERATED,
        f"# {p['name']}\n\n`{p['id']}` &middot; **{p['role']}** &middot; {p['service']} "
        f"&middot; {p['type'].title()} prompt &middot; "
        f"**{(p.get('score') or {}).get('total', '?')}/20**",
        f"**Target deliverables:** {deliverables}",
        "## Fill these in\n\n" + inputs,
        "## Prompt (CARE + G.E.T.)\n\n```text\n" + render(p, "care") + "\n```",
        "## Used in these delivery contexts\n\n" + contexts,
        "## Scorecard\n\n" + score_table(p)
        + (f"\n\n**Notes:** {(p.get('score') or {}).get('notes')}"
           if (p.get('score') or {}).get('notes') else ""),
        "## Other frameworks\n\n"
        f"```bash\npython tools/convert.py {p['id']} --format co-star\n"
        f"python tools/convert.py {p['id']} --to-skill\n```\n\n"
        + fidelity_table(p)
        + "\n\nConversion is lossy by design: a framework with no Example slot cannot carry "
          "the worked example, and the score drops accordingly. See "
          "[formats/README.md](../../../formats/README.md).",
        "## Provenance\n\n" + "\n".join(
            f"- **{k.replace('_', ' ').title()}:** {v}" for k, v in (p.get("provenance") or {}).items()
        ),
    ])


def build_index(prompts: list[dict], check: bool) -> None:
    by_role: dict[str, list[dict]] = defaultdict(list)
    for p in prompts:
        by_role[p["role"]].append(p)

    lines = [
        "# Index", "",
        f"{len(prompts)} prompts &middot; {len({p['service'] for p in prompts})} BA services "
        f"&middot; {len(by_role)} roles &middot; mean score "
        f"{sum((p.get('score') or {}).get('total', 0) for p in prompts) / len(prompts):.2f}/20", "",
        "Generated by `tools/build.py`. Don't know which prompt you need? Don't browse this - "
        "use [`skills/ba-prompt-router`](skills/ba-prompt-router/SKILL.md) and describe your "
        "situation instead.", "",
    ]
    for role in sorted(by_role):
        lines += [f"## {role}", "", "| ID | Prompt | Type | Service | Score |",
                  "| --- | --- | --- | --- | --- |"]
        for p in sorted(by_role[role], key=lambda x: x["id"]):
            rel = p["_path"].relative_to(ROOT).as_posix()
            lines.append(
                f"| `{p['id']}` | [{p['name']}]({rel}) | {p['type']} | {p['service']} "
                f"| {(p.get('score') or {}).get('total', '?')}/20 |"
            )
        lines.append("")
    emit(ROOT / "INDEX.md", "\n".join(lines), check)


def build_catalogue(prompts: list[dict], check: bool) -> None:
    """Machine-readable catalogue - the file an app or an agent should load."""
    payload = {
        "version": "1.0",
        "count": len(prompts),
        "frameworks": {k: {"label": v["label"], "note": v["note"]} for k, v in FORMATS.items()},
        "prompts": [
            {
                "id": p["id"], "name": p["name"], "type": p["type"], "role": p["role"],
                "service": p["service"], "deliverables": p.get("deliverables", []),
                "delivery_contexts": p.get("delivery_contexts", []),
                "audience": p["audience"], "task": p["task"],
                "modes": p.get("modes", []), "inputs": p.get("inputs", []),
                "score": (p.get("score") or {}).get("total"),
                "path": p["_path"].relative_to(ROOT).as_posix(),
            }
            for p in prompts
        ],
    }
    emit(ROOT / "catalogue.json", json.dumps(payload, indent=2, ensure_ascii=False), check)


def build_stats(prompts: list[dict], check: bool) -> None:
    roles = Counter(p["role"] for p in prompts)
    types = Counter(p["type"] for p in prompts)
    scores = Counter((p.get("score") or {}).get("total") for p in prompts)
    decomposable = [p for p in prompts if len(p.get("modes") or []) > 1]
    lines = [
        "# Library statistics", "",
        "Generated by `tools/build.py`.", "",
        f"- **Prompts:** {len(prompts)}",
        f"- **Services:** {len({p['service'] for p in prompts})}",
        f"- **Mean score:** {sum((p.get('score') or {}).get('total', 0) for p in prompts) / len(prompts):.2f}/20",
        f"- **Multi-mode prompts awaiting decomposition:** {len(decomposable)} "
        f"({sum(len(p['modes']) for p in decomposable)} candidate single-task units)", "",
        "## By role", "", "| Role | Prompts |", "| --- | --- |",
        *[f"| {k} | {v} |" for k, v in sorted(roles.items())], "",
        "## By type", "", "| Type | Prompts |", "| --- | --- |",
        *[f"| {k} | {v} |" for k, v in sorted(types.items())], "",
        "## Score distribution", "", "| Score | Prompts |", "| --- | --- |",
        *[f"| {k}/20 | {v} |" for k, v in sorted(scores.items(), reverse=True)], "",
        "> Paper scores skew high: the library was written against this rubric. Dry-run, "
        "consistency and hand-off tests on real (de-identified) work are the stronger evidence - "
        "log those in [`field-reports/`](field-reports/).",
    ]
    emit(ROOT / "docs" / "statistics.md", "\n".join(lines), check)


def build_formats(prompts: list[dict], check: bool) -> None:
    """formats/README.md, generated from the registry so it cannot drift."""
    reference = next((p for p in prompts if p["id"] == "BB-01-D1"), prompts[0])
    rows, sections = [], []
    for key, meta in FORMATS.items():
        f = fidelity(reference, key)
        lost = ", ".join(f["criteria_lost"]) or "-"
        rows.append(f"| `{key}` | {meta['label']} | {f['converted_total']} / 20 | {lost} |")
        sections.append(
            f"### {meta['label']} - `{key}`\n\n{meta['note']}\n\n"
            f"```bash\npython tools/convert.py {reference['id']} --format {key}\n```\n\n"
            f"<details><summary>{reference['id']} rendered as {meta['label']}</summary>\n\n"
            f"```text\n{render(reference, key)}\n```\n\n</details>"
        )
    lines = [
        "# Prompt frameworks", "",
        "The library is written in CARE + G.E.T., but CARE is a storage format, not a",
        "commitment. Each prompt is stored as **fields**, not as one blob of text, so it",
        "can be re-rendered into any framework below - or into an agent skill.", "",
        "## Conversion is lossy, and the repo says by how much", "",
        "A framework with no Example slot cannot carry the worked example. A framework",
        "with no place for verification rules drops them. Each renderer declares which of",
        "the ten rubric criteria its slots can actually carry, so the cost is a number",
        "rather than a shrug:", "",
        "```bash", "python tools/convert.py BB-01-D1 --format rtf --fidelity", "```", "",
        f"Below, `{reference['id']}` ({(reference.get('score') or {}).get('total')}/20 in CARE) "
        "converted into each framework:", "",
        "| Flag | Framework | Score after conversion | Criteria lost |",
        "| --- | --- | --- | --- |", *rows, "",
        "Pick a lossy framework deliberately - for a short input box, or a house standard -",
        "not by accident.", "",
        "## Adding a framework", "",
        "Add a renderer to `tools/formats.py` and register it in `FORMATS` with the set of",
        "criteria its slots can carry. That set is the honest part: claiming a framework",
        "carries a criterion it has no slot for makes the fidelity report lie.", "",
        "## The frameworks", "",
    ]
    emit(ROOT / "formats" / "README.md", "\n".join(lines) + "\n\n" + "\n\n".join(sections), check)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    prompts = all_prompts()
    if not prompts:
        print("No prompts found. Run tools/extract_workbook.py first.", file=sys.stderr)
        return 1

    for p in prompts:
        write = p["_path"]
        body = prompt_body(p)
        if check:
            if p["_body"].rstrip() != body.rstrip():
                changes.append(str(write.relative_to(ROOT)).replace("\\", "/"))
        else:
            write_prompt(write, p, body)

    build_formats(prompts, check)
    build_index(prompts, check)
    build_catalogue(prompts, check)
    build_stats(prompts, check)

    if check and changes:
        print("Out of date - run `python tools/build.py`:", file=sys.stderr)
        for c in sorted(set(changes))[:20]:
            print(f"  {c}", file=sys.stderr)
        if len(set(changes)) > 20:
            print(f"  ... and {len(set(changes)) - 20} more", file=sys.stderr)
        return 1
    print(f"Built {len(prompts)} prompts, INDEX.md, catalogue.json, formats/README.md, docs/statistics.md"
          + (f" ({len(set(changes))} file(s) changed)" if changes else " (no changes)"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
